################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
heading = "¿Qué te gustaría <br> leer hoy?"

[en.about_me]
title = "Hi, I am Alex!"
image = "images/author.jpg"
bio = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vel in in donec iaculis tempus odio nunc laoreet . Libero ullamcorper."
