############# english navigation ##############

[[main]]
name = "Inicio"
URL = "/"
weight = 1

[[main]]
name = "Nosotros"
URL = "about-us/"
weight = 2
  
[[main]]
name = "Contacto"
URL = "contact/"
weight = 3


# footer menu
[[footer]]
name = "Políticas de privacidad"
URL = "privacy-policy/"
weight = 1

[[footer]]
name = "Términos y condiciones"
URL = "terms-conditions/"
weight = 2